
#global variable names to make code more readable
SPY = "SPX_Equities"
FIXED_INCOME = "LUATTRUU_Fixed_Income"
REIT = "RMZ_REITs"
GOLD = "XAU_Gold"
CSI = "CSI_BARC_HY_SPREAD"
YIELDSPREAD = "USYC2Y10_10y_2y"
CPI = "CPI_YOY_US_CPI"
GDP_GROWTH = "GDP_CURY_US_GDP_GROWTH"
UNEMPLOYMENT = "USURTOT_US_UNEMPLOYMENT"
SPY_PE_RATIO = "S&P500_PE_PE_Ratio_S&P"
LUMBER = "LB1_Lumber"
OIL = "CL1_OIL_WTI"
CONSUMER_CONFIDENCE = "CONSSENT_Consumer_Confidence"
SAVINGS = "PIDSDPS_SAVINGS_DISP_INC"
COPPER_GOLD_RATIO = "GLDHG_COPPER_GOLD_RATIO"

#dictionary with all parameters used for input
PARAM_DICT = {CSI, YIELDSPREAD, CPI, GDP_GROWTH, UNEMPLOYMENT, SPY_PE_RATIO, LUMBER, OIL, CONSUMER_CONFIDENCE, SAVINGS, COPPER_GOLD_RATIO}

#dictionary with all assets
ASSET_DICT = {REIT, GOLD, FIXED_INCOME, SPY}

RISK_PARITY = "Risk Parity"
MAX_SHARPE = "Max Sharpe"
MAX_PROFIT = "Max Profit"
EQUAL = "Equal Weights"
GMV = "GMV"